# SecRule REQUEST_URI "@beginsWith /api/" \
#     "id:1002,phase:1,pass,nolog,ctl:ruleRemoveTargetById=920420;ARGS"
# @TODO Cloe: j'ai du rajouter cette regle pour exposer ma route, a voir a l'integrer avec ton systeme
SecRule REQUEST_URI "@beginsWith /api/" \
	"id:1002,phase:1,pass,nolog,ctl:ruleRemoveById=911100"

SecRule REQUEST_URI "@beginsWith /kibana/" \
    "id:1004,phase:1,pass,nolog,ctl:ruleEngine=Off"

SecRule REQUEST_URI "@beginsWith /grafana/" \
    "id:1005,phase:1,pass,nolog,ctl:ruleEngine=Off"