export const CHESS_ACTIONS = {
  TOGGLE_DEBUG: "TOGGLE_DEBUG",
  SET_VIEW_PLIES: "SET_VIEW_PLIES",
  APPEND_MOVE_LOG_ENTRY: "APPEND_MOVE_LOG_ENTRY",
  SET_MOVE_FEEDBACK: "SET_MOVE_FEEDBACK",
  CLEAR_MOVE_FEEDBACK: "CLEAR_MOVE_FEEDBACK",
  APPLY_SERVER_SNAPSHOT: "APPLY_SERVER_SNAPSHOT",
  APPLY_LOCAL_POSITION: "APPLY_LOCAL_POSITION",
  RESET_MATCH: "RESET_MATCH",
};

export const ACTIVE_MATCH_STATUSES = new Set(["active"]);

export const FINISHED_MATCH_STATUSES = new Set([
  "checkmate",
  "stalemate",
  "draw",
  "resigned",
  "timeout",
]);
