version: '3.8'

networks:
  frontend_net:
  backend_net:
  monitor_net:

services:
  # bdd
  db:
    image: postgres:15
    container_name: transcendence_db
    volumes:
      - ./database/data:/var/lib/postgresql/data
    env_file: .env # Les secrets ne sont pas sur Git 
    restart: always
    networks:
      - backend_net

  backend:
    build: ./backend
    container_name: transcendence_back
    volumes:
      - ./backend:/app
    environment:
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - backend_net
    restart: always

  # Alexis - frontend
  frontend:
    build: ./frontend
    container_name: transcendence_front
    restart: always
    networks:
      - frontend_net

  # Cloé - Cyber
  nginx:
    build: ./nginx
    container_name: transcendence_nginx
    ports:
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    restart: always
    networks:
      - frontend_net
      - monitor_net
      - backend_net

  # Cloe - Monitoring
  prometheus:
    image: prom/prometheus
    container_name: transcendence_prom
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=https://localhost/prometheus'
    networks:
      - monitor_net
      - backend_net
  
  node_exporter:
    image: prom/node-exporter:latest
    container_name: transcendence_node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)'
    networks:
      - monitor_net
    restart: always

  grafana:
    image: grafana/grafana
    container_name: transcendence_grafana
    # deleted port for security reason
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    restart: always
    networks:
      - monitor_net

# Théo/Mileum - Log Management
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elastic
    env_file: .env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certs/elasticsearch.crt
      - xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certs/elasticsearch.key
    volumes:
      - ./elasticsearch/certs:/usr/share/elasticsearch/config/certs:ro
    restart: always
    ports:
      - "9200:9200"
    networks:
      - monitor_net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    env_file: .env
    environment:
      - SERVER_BASEPATH="/kibana"
      - SERVER_REWRITEBASEPATH="true"
    depends_on:
      - elasticsearch
    restart: always
    # On expose pas le port 5601 sur le net on passe par le 443
    networks:
      - monitor_net

  logstash:
    build: ./logstash
    container_name: logstash
    env_file: .env
    volumes:
      - ./certs:/usr/share/logstash/config/certs
    environment:
      - MONITORING_ENABLED=false
      - XPACK_MONITORING_ENABLED=false
      - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
    depends_on:
      - elasticsearch
    networks:
      - monitor_net
      - backend_net
    restart: always
volumes:
  grafana_data: