# Generated by Django 5.0.2 on 2026-04-06 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_localuser_avatar_localuser_bio_localuser_elo_blitz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Total duration of the game in seconds', null=True)),
                ('player_black', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_black', to='accounts.localuser')),
                ('player_white', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_white', to='accounts.localuser')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chess_games_won', to='accounts.localuser')),
            ],
            options={
                'db_table': 'games',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.PositiveIntegerField(help_text='Global order of the move in the game (e.g., 1, 2, 3...)')),
                ('san_notation', models.CharField(help_text='PGN notation of the move', max_length=20)),
                ('piece_played', models.CharField(help_text="Explicit string of the piece played (e.g., 'pawn', 'knight', 'bishop', 'rook', 'queen', 'king')", max_length=20)),
                ('time_taken_ms', models.PositiveIntegerField(help_text='Time taken to think and play this move in milliseconds')),
                ('material_advantage', models.IntegerField(default=0, help_text='Material advantage after the move (e.g., +1, -3)')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_played', to='accounts.localuser')),
            ],
            options={
                'db_table': 'moves',
                'ordering': ['game', 'move_number'],
            },
        ),
    ]
