# Generated by Django 5.0.2 on 2026-04-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ended_at',
        ),
        migrations.AlterField(
            model_name='game',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
