# Generated by Django 5.0.2 on 2026-04-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_ended_at_alter_game_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='increment',
            field=models.PositiveIntegerField(blank=True, help_text='Increment per move in seconds', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='time_control',
            field=models.PositiveIntegerField(blank=True, help_text='Initial time control in seconds', null=True),
        ),
    ]
