# Generated by Django 5.0.2 on 2026-04-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_match_metadata_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='elo_delta_black',
            field=models.IntegerField(default=0, help_text='ELO points gained/lost by black player'),
        ),
        migrations.AddField(
            model_name='game',
            name='elo_delta_white',
            field=models.IntegerField(default=0, help_text='ELO points gained/lost by white player'),
        ),
    ]
