# Generated by Django 5.0.2 on 2026-04-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_elo_delta_black_game_elo_delta_white'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='elo_black_before',
            field=models.IntegerField(default=1200, help_text='ELO of black player before match'),
        ),
        migrations.AddField(
            model_name='game',
            name='elo_white_before',
            field=models.IntegerField(default=1200, help_text='ELO of white player before match'),
        ),
    ]
