apiVersion: 1

contactPoints:
  - orgId: 1
    name: 'Alert_Admin_Email'
    receivers:
      - uid: mailhog_1
        type: email
        settings:
          addresses: admin@transcendence.com

policies:
  - orgId: 1
    receiver: 'Alert_Admin_Email'