# Generated by Django 5.0.2 on 2026-04-05 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_localuser_is_2fa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='localuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='localuser',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='localuser',
            name='elo_blitz',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='localuser',
            name='elo_bullet',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='localuser',
            name='elo_rapid',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='localuser',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='localuser',
            name='games_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='localuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localuser',
            name='level',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_sent', to='accounts.localuser')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to='accounts.localuser')),
            ],
            options={
                'db_table': 'friendships',
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
