# Generated by Django 5.0.2 on 2026-04-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_friendship_blocked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='localuser',
            name='games_draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='localuser',
            name='games_lost',
            field=models.IntegerField(default=0),
        ),
    ]
