# Generated by Django 5.0.2 on 2026-04-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_localuser_client_prefs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localuser',
            name='client_prefs',
            field=models.JSONField(blank=True, default=None, help_text='Persistent UI/audio preferences.', null=True),
        ),
    ]
