"""
Django settings for transcendence_backend project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import hvac
from pathlib import Path

import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


def _env_bool(name, default=False):
    raw = os.environ.get(name)
    if raw is None:
        return default
    return str(raw).strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name, default_values):
    raw = os.environ.get(name)
    if not raw:
        return default_values
    values = [item.strip() for item in raw.split(',') if item.strip()]
    return values or default_values

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# LOGS_DIR ensures we have a dedicated writable folder for local JSON ELK logs
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-u=m6iv)64!pt2i$(_khl29qg8797dvq-93at8z$brl4u^uv0b*'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', ['backend', 'localhost', '127.0.0.1', '0.0.0.0'])

# CSRF_TRUSTED_ORIGINS : trust domain
CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS', ['https://localhost:8443', 'https://127.0.0.1:8443'])

# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

SESSION_COOKIE_SECURE = _env_bool('DJANGO_SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = _env_bool('DJANGO_CSRF_COOKIE_SECURE', not DEBUG)
SESSION_COOKIE_HTTPONLY = True

# Ne pas réécraser ALLOWED_HOSTS / CSRF_TRUSTED_ORIGINS : ils viennent des lignes ci-dessus
# (variables d’environnement DJANGO_*), nécessaires pour LAN / domaine de prod.

# 4. SameSite : 'Lax' est généralement le plus compatible pour OAuth
SESSION_COOKIE_SAMESITE = 'Lax'

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'accounts',
    'game',
    'chat',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_prometheus',
]

# Petit hack car daphne ne s'import pas a tous les coups. @TODO Trouver une solution plus propre.
try:
    import daphne  # noqa: F401
except ImportError:
    daphne = None
else:
    INSTALLED_APPS.insert(0, 'daphne')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'transcendence_backend.urls'

CORS_ALLOWED_ORIGINS = _env_list('DJANGO_CORS_ALLOWED_ORIGINS', ["https://localhost:8443", "http://localhost:5173"])

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'transcendence_backend.wsgi.application'
ASGI_APPLICATION = 'transcendence_backend.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.environ.get('DB_NAME'),
#         'USER': os.environ.get('DB_USER'),
#         'PASSWORD': os.environ.get('DB_PASSWORD'),
#         'HOST': os.environ.get('DB_HOST', 'db'),
#         'PORT': '5432',
#     }
# }

# VAULT
vault_url = os.environ.get('VAULT_ADDR', 'https://vault:8202')
vault_token = os.environ.get('VAULT_TOKEN')

# init a vide
db_user = os.environ.get('DB_USER', 'postgres')
db_password = os.environ.get('DB_PASSWORD', '')
db_name = os.environ.get('DB_NAME', 'transcendence')
redis_password = ''
ft_client_id = ''
ft_client_secret = ''
email_password = ''
elastic_password = ''

if vault_token:
    try:
        # cert_path = '/app/certs/nginx.crt'
        client = hvac.Client(url=vault_url, token=vault_token, verify=False)
        read_response = client.secrets.kv.v2.read_secret_version(path='database')
        secrets = read_response['data']['data']
        
        db_user = secrets.get('db_user', db_user)
        db_password = secrets.get('db_password', db_password)
        db_name = secrets.get('db_name', db_name)
        
        redis_password = secrets.get('redis_pass', redis_password)
        ft_client_id = secrets.get('ft_client', ft_client_id)
        ft_client_secret = secrets.get('ft_secret', ft_client_secret)
        email_password = secrets.get('email_pass', email_password)
        elastic_password = secrets.get('elastic_pass', elastic_password)
        
        print("All the secrets are now in vault!")
    except Exception as e:
        print(f"Connection error with vault : {e}")

REDIS_PASSWORD = redis_password
FORTYTWO_CLIENT_ID = ft_client_id
FORTYTWO_CLIENT_SECRET = ft_client_secret
EMAIL_HOST_PASSWORD = email_password
ELASTIC_PASSWORD = elastic_password

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': db_name,
        'USER': db_user,
        'PASSWORD': db_password,
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': '5432',
    }
}


# 1. Define the Redis connection
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        # Notice we use the service name 'redis' from your docker-compose
        "LOCATION": f"redis://:{REDIS_PASSWORD}@redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# 2. Tell Django to route all 'request.session' calls to Redis
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
 
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                f"redis://:{REDIS_PASSWORD}@redis:6379/0"
            ],
        },
    },
}


# Email Configuration
# https://docs.djangoproject.com/en/5.0/topics/email/

# For development: output emails to console
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend'
) if DEBUG else 'django.core.mail.backends.smtp.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@transcendence.local')

# SMTP configuration (for production)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json_formatter': {
            '()': 'utils.json_logger.JsonFormatter',
        },
    },
    'handlers': {
        'app_file': {
            'level': 'INFO', # Includes INFO, WARNING, ERROR, CRITICAL
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'application.log'),
            'maxBytes': 1024 * 1024 * 50, # 50 MB
            'backupCount': 3,
            'formatter': 'json_formatter',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        # Core Django Logger (Requests, SQL, Errors)
        'django': {
            'handlers': ['app_file', 'console'],
            'level': 'INFO',  # Restored INFO and console so the developer terminal is not empty
            'propagate': True,
        },
        # Dedicated Application Loggers
        'transcendence': {
            'handlers': ['app_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'frontend': {
            'handlers': ['app_file'],
            'level': 'INFO',
            'propagate': False,
        }
    },
}
# Celery Configuration
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", f"redis://:{REDIS_PASSWORD}@redis:6379/0")
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
