# Generated by Django 5.0.2 on 2026-04-13 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_control_seconds', models.PositiveIntegerField(default=600)),
                ('increment_seconds', models.PositiveSmallIntegerField(default=0)),
                ('competitive', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('cancel_reason', models.CharField(blank=True, max_length=40, null=True)),
                ('game_id', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_invites', to='chat.conversation')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_game_invites', to='accounts.localuser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_game_invites', to='accounts.localuser')),
                ('source_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_invite_meta', to='chat.message')),
            ],
            options={
                'db_table': 'chat_game_invites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['receiver', 'status'], name='chat_game_i_receive_8e0f9f_idx'), models.Index(fields=['sender', 'status'], name='chat_game_i_sender__2d3318_idx'), models.Index(fields=['status', 'expires_at'], name='chat_game_i_status__968838_idx')],
                'constraints': [models.CheckConstraint(check=models.Q(('sender', models.F('receiver')), _negated=True), name='chat_game_invite_sender_receiver_different'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('sender',), name='chat_one_pending_outgoing_invite_per_sender')],
            },
        ),
    ]
