# Generated by Django 5.0.2 on 2026-04-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_gameinvite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gameinvite',
            new_name='chat_game_i_receive_a1d5b1_idx',
            old_name='chat_game_i_receive_8e0f9f_idx',
        ),
        migrations.RenameIndex(
            model_name='gameinvite',
            new_name='chat_game_i_sender__fd2b64_idx',
            old_name='chat_game_i_sender__2d3318_idx',
        ),
        migrations.RenameIndex(
            model_name='gameinvite',
            new_name='chat_game_i_status_61154c_idx',
            old_name='chat_game_i_status__968838_idx',
        ),
    ]
