input {
  file {
    path => "/var/log/nginx/access.log"
    start_position => "beginning"
    type => "nginx-access"
  }
}

filter {
  if [type] == "nginx-access" {
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
    mutate {
      convert => { "response" => "integer" }
      convert => { "bytes" => "integer" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["https://elasticsearch:9200"]
    ssl_certificate_verification => false
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"

    # Disable data streams to use classic index naming
    data_stream => "false"
    index => "logstash-%{+YYYY.MM.dd}" 
  }
  
  stdout { codec => rubydebug }
}