input {
  heartbeat {
    interval => 5
    message => "End-to-end test successful"
  }
}

output {
  elasticsearch {
    hosts => ["https://elasticsearch:9200"]
    ssl_certificate_verification => false # Skip verification for self-signed certs
    user => "elastic"
    password => "${ELASTIC_PASSWORD}" # Use your env variable

    data_stream => "true"
    data_stream_type => "logs"
    data_stream_dataset => "heartbeat"
    data_stream_namespace => "dev"
  }
  
  # Keep this to see the results in your terminal too
  stdout { codec => rubydebug }
}